package quiz;
import java.io.*;
import java.net.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.stream.*;
public final class Server {
 final Bank bank;final Model.Store store;final File storeFile;final Map<String,Peer> online=new ConcurrentHashMap<>();final Map<String,Match> matches=new ConcurrentHashMap<>();final Map<String,Invite> invites=new ConcurrentHashMap<>();final ScheduledExecutorService timer=Executors.newScheduledThreadPool(2);final ExecutorService workers=Executors.newCachedThreadPool();
 record Invite(String from,String to,String topic,String level){}
 Server(Path folder)throws IOException{Files.createDirectories(folder);bank=new Bank(folder.resolve("questions.txt"));storeFile=folder.resolve("users.dat").toFile();store=Model.Store.read(storeFile);}
 static final class Peer {final Socket socket;final DataInputStream in;final DataOutputStream out;volatile String name;Peer(Socket s)throws IOException{socket=s;in=new DataInputStream(s.getInputStream());out=new DataOutputStream(s.getOutputStream());}void send(String... a){try{Wire.send(out,a);}catch(IOException e){try{socket.close();}catch(IOException ignored){}}}}
 final class Match {
  final String id=UUID.randomUUID().toString(),left,right,topic,level;final Set<String> used=new HashSet<>();Model.SetData set;long start,deadline;boolean done;int[] correct=new int[2];long[] duration=new long[2];boolean[] submitted=new boolean[2],rematch=new boolean[2];
  Match(String a,String b,String t,String l){left=a;right=b;topic=t;level=l;}
  int index(String name){return name.equals(left)?0:name.equals(right)?1:-1;}
  synchronized void start(){set=bank.pick(topic,level,used);if(set==null){close("Không tìm thấy bộ đề");return;}used.add(set.id());Arrays.fill(submitted,false);Arrays.fill(rematch,false);Arrays.fill(correct,0);Arrays.fill(duration,0);done=false;start=System.nanoTime();deadline=start+TimeUnit.SECONDS.toNanos(set.duration());
   ArrayList<String> msg=new ArrayList<>(List.of("MATCH",id,left,right,topic,level,set.id(),""+set.duration()));for(Model.Question q:set.questions()){msg.add(q.text());msg.addAll(Arrays.asList(q.choices()));}
   send(left,msg.toArray(String[]::new));send(right,msg.toArray(String[]::new));timer.schedule(()->{synchronized(Match.this){finishExpired();}},set.duration(),TimeUnit.SECONDS);broadcast();}
  synchronized void submit(String name,String[] a){int i=index(name);if(i<0||done||submitted[i])return;long now=System.nanoTime();if(now>=deadline){finishExpired();return;}if(a.length!=12){send(name,"ERROR","Phải gửi đúng 10 đáp án");return;}int points=0;for(int k=0;k<10;k++){try{int v=Integer.parseInt(a[k+2]);if(v!= -1 && (v<0||v>3)){send(name,"ERROR","Đáp án không hợp lệ");return;}if(v==set.questions().get(k).answer())points++;}catch(NumberFormatException e){send(name,"ERROR","Đáp án không hợp lệ");return;}}
   correct[i]=points;duration[i]=TimeUnit.NANOSECONDS.toMillis(now-start);submitted[i]=true;send(name,"SUBMITTED","Đã nhận bài");if(submitted[0]&&submitted[1])finish();}
  void finishExpired(){if(done)return;for(int i=0;i<2;i++)if(!submitted[i]){submitted[i]=true;duration[i]=set.duration()*1000L;correct[i]=0;}finish();}
  void finish(){if(done)return;done=true;String winner="HÒA";if(correct[0]!=correct[1])winner=correct[0]>correct[1]?left:right;else if(Math.abs(duration[0]-duration[1])>1000)winner=duration[0]<duration[1]?left:right;
   synchronized(store){if(!winner.equals("HÒA")){String loser=winner.equals(left)?right:left;store.users.get(winner).score+=2;store.users.get(loser).score=Math.max(0,store.users.get(loser).score-1);}store.results.add(new Model.Result(id,left,right,topic,level,set.id(),correct[0],correct[1],duration[0],duration[1],set.duration(),winner));store.save(storeFile);}
   ArrayList<String> msg=new ArrayList<>(List.of("RESULT",winner,left+": "+correct[0]+" câu, "+duration[0]+" ms",right+": "+correct[1]+" câu, "+duration[1]+" ms","Chơi tiếp? Chọn Có hoặc Không"));for(Model.Question q:set.questions())msg.add(""+q.answer());String[] resPacket=msg.toArray(String[]::new);send(left,resPacket);send(right,resPacket);broadcast();}
  synchronized void vote(String name,boolean yes){int i=index(name);if(i<0||!done)return;if(!yes){close(name+" không chơi tiếp");return;}rematch[i]=true;send(name,"INFO","Đang chờ đối thủ đồng ý tái đấu");if(rematch[0]&&rematch[1])start();}
  synchronized void disconnected(String name){if(!done){int i=index(name);if(i>=0){submitted[i]=true;correct[i]=0;duration[i]=set.duration()*1000L;if(submitted[0]&&submitted[1])finish();}}close(name+" đã rời phòng");}
  void close(String reason){matches.remove(left,this);matches.remove(right,this);send(left,"CLOSED",reason);send(right,"CLOSED",reason);broadcast();}
 }
 void send(String name,String... a){Peer p=online.get(name);if(p!=null)p.send(a);}
 synchronized void broadcast(){StringBuilder b=new StringBuilder();synchronized(store){online.keySet().stream().sorted().forEach(n->b.append(n).append(';').append(store.users.get(n).score).append(';').append(matches.containsKey(n)?"Đang bận":"Đang rỗi").append('|'));}String s=b.toString();for(Peer p:online.values())p.send("LOBBY",s);}
 void serve(Peer p){try(p.socket){while(true){String[] a=Wire.read(p.in);handle(p,a);}}catch(Exception ignored){}finally{String n=p.name;if(n!=null&&online.remove(n,p)){Invite inv=invites.remove(n);if(inv!=null)send(inv.from(),"DECLINED",n+" đã thoát");invites.entrySet().removeIf(e->e.getValue().from().equals(n));Match m=matches.get(n);if(m!=null)m.disconnected(n);broadcast();}}}
 void handle(Peer p,String[] a){try{String type=a[0];if(type.equals("REGISTER")){String n=Wire.field(a,1).trim(),pass=Wire.field(a,2);if(!n.matches("[A-Za-z0-9_]{3,24}")||pass.length()<4){p.send("ERROR","Tên 3-24 ký tự chữ/số/_; mật khẩu từ 4 ký tự");return;}synchronized(store){if(store.users.containsKey(n)){p.send("ERROR","Tên đã tồn tại");return;}store.users.put(n,new Model.User(n,Security.hashPassword(pass)));store.save(storeFile);}p.send("INFO","Đăng ký thành công");return;}
  if(type.equals("LOGIN")){if(p.name!=null)return;String n=Wire.field(a,1);synchronized(store){Model.User u=store.users.get(n);if(u==null||!Security.verifyPassword(Wire.field(a,2),u.password)){p.send("ERROR","Sai tài khoản hoặc mật khẩu");return;}if(Security.isLegacy(u.password)){u.password=Security.hashPassword(Wire.field(a,2));store.save(storeFile);}if(online.putIfAbsent(n,p)!=null){p.send("ERROR","Tài khoản đang đăng nhập");return;}p.name=n;}p.send("WELCOME",n,String.join("|",bank.topics()));broadcast();return;}
  if(p.name==null){p.send("ERROR","Cần đăng nhập");return;}
  switch(type){case "CHALLENGE"->{String to=Wire.field(a,1),topic=Wire.field(a,2),level=Wire.field(a,3);if(to.equals(p.name)||!online.containsKey(to)||matches.containsKey(to)||matches.containsKey(p.name)||invites.containsKey(to)||!bank.topics().contains(topic)||!Arrays.asList(Model.LEVELS).contains(level)){p.send("ERROR","Không thể gửi lời mời");return;}Model.SetData sample=bank.pick(topic,level,new HashSet<>());if(sample==null){p.send("ERROR","Chưa có bộ đề");return;}invites.put(to,new Invite(p.name,to,topic,level));send(to,"INVITE",p.name,topic,level,"10",""+sample.duration());p.send("INFO","Đã gửi lời mời đến "+to);timer.schedule(()->{Invite inv=invites.get(to);if(inv!=null&&inv.from().equals(p.name)&&invites.remove(to,inv))send(p.name,"DECLINED","Lời mời hết hạn");},30,TimeUnit.SECONDS);}
   case "ACCEPT","REJECT"->{Invite inv=invites.remove(p.name);if(inv==null||!inv.from().equals(Wire.field(a,1))){p.send("ERROR","Lời mời không còn hiệu lực");return;}if(type.equals("REJECT")||!online.containsKey(inv.from())||matches.containsKey(inv.from())||matches.containsKey(p.name)){send(inv.from(),"DECLINED",p.name+" từ chối hoặc không còn sẵn sàng");return;}Match m=new Match(inv.from(),p.name,inv.topic(),inv.level());matches.put(m.left,m);matches.put(m.right,m);m.start();}
   case "SUBMIT"->{Match m=matches.get(p.name);if(m!=null&&m.id.equals(Wire.field(a,1)))m.submit(p.name,a);}
   case "REMATCH"->{Match m=matches.get(p.name);if(m!=null)m.vote(p.name,Wire.field(a,1).equals("YES"));}
   case "LEAVE"->{Match m=matches.get(p.name);if(m!=null)m.disconnected(p.name);}
   case "EMOTE"->{Match m=matches.get(p.name);if(m!=null){String to=p.name.equals(m.left)?m.right:m.left;send(to,"EMOTE",p.name,Wire.field(a,1));}}
   case "LEADERBOARD"->leaderboard(p);
   case "HISTORY"->history(p);
   default->p.send("ERROR","Lệnh không hợp lệ");}
 }catch(Exception e){p.send("ERROR",e.getMessage()==null?"Lỗi xử lý":e.getMessage());}}
 void leaderboard(Peer p){StringBuilder b=new StringBuilder();synchronized(store){List<Model.User> users=new ArrayList<>(store.users.values());Map<String,Double> opponent=new HashMap<>(),speed=new HashMap<>();for(Model.User u:users){List<Model.Result> rs=store.results.stream().filter(r->r.left().equals(u.name)||r.right().equals(u.name)).toList();opponent.put(u.name,rs.stream().mapToInt(r->{Model.User other=store.users.get(r.left().equals(u.name)?r.right():r.left());return other==null?0:other.score;}).average().orElse(0));speed.put(u.name,rs.stream().filter(r->r.winner().equals(u.name)).mapToDouble(r->(r.left().equals(u.name)?r.leftMs():r.rightMs())/(r.duration()*1000.0)).average().orElse(Double.POSITIVE_INFINITY));}
 users.sort(Comparator.comparingInt((Model.User u)->u.score).reversed().thenComparing(Comparator.comparingDouble((Model.User u)->opponent.get(u.name)).reversed()).thenComparingDouble(u->speed.get(u.name)).thenComparing(u->u.name));for(Model.User u:users)b.append(u.name).append(';').append(u.score).append(';').append(String.format(Locale.ROOT,"%.2f",opponent.get(u.name))).append(';').append(Double.isInfinite(speed.get(u.name))?"—":String.format(Locale.ROOT,"%.3f",speed.get(u.name))).append('|');}p.send("LEADERBOARD",b.toString());}
 void history(Peer p){StringBuilder b=new StringBuilder();synchronized(store){for(Model.Result r:store.results)if(r.left().equals(p.name)||r.right().equals(p.name))b.append(r.topic()).append(" / ").append(r.level()).append(" / ").append(r.setId()).append(": ").append(r.left()).append(" ").append(r.leftCorrect()).append("–").append(r.rightCorrect()).append(" ").append(r.right()).append(" → ").append(r.winner()).append('\n');}p.send("HISTORY",b.toString());}
 public static void main(String[] args)throws Exception{int port=args.length>0?Integer.parseInt(args[0]):5050;Path folder=Path.of(args.length>1?args[1]:"data");Server app=new Server(folder);try(ServerSocket socket=new ServerSocket(port)){System.out.println("Quiz server: port "+port+", data "+folder.toAbsolutePath());try{String ip=InetAddress.getLocalHost().getHostAddress();System.out.println("Dia chi IP may chu (de cac may khac ket noi): "+ip+":"+port);}catch(Exception ignored){}while(true){Peer p=new Peer(socket.accept());app.workers.submit(()->app.serve(p));}}}
}
